USE [Xclinic_HML]
GO

/****** Object:  View [dbo].[EXVW_MEDICOSCONVENIOS]    Script Date: 11/05/2022 15:12:52 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO





ALTER VIEW [dbo].[EXVW_MEDICOSCONVENIOS]
AS
SELECT DISTINCT
		CONVERT(VARCHAR(50), C.CONVENIOID) + '_' + CONVERT(VARCHAR(50),C.CONVENIOCOD) + '_' + CONVERT(VARCHAR(50),ISNULL(P.PLANOID,C.CONVENIOID)) AS INSURANCE_LID,
		cast(M.MEDICOID as varchar) as RESOURCE_LID
		FROM MEDICOS M WITH(NOLOCK)
		--INNER JOIN MEDCONVENIOSNAOATENDIDOS MCP ON MCP.MEDICOID = M.MEDICOID
		INNER JOIN CONVENIOS C WITH(NOLOCK) ON C.CONVENIOID = C.CONVENIOID
		INNER JOIN CONVENIOSPLANOS P WITH(NOLOCK) ON P.CONVENIOID = C.CONVENIOID --AND C.PLANOID=P.PLANOID
		--INNER JOIN MEDPLANOSNAOATENDIDOS MPN ON MPN.MEDICOID = M.MEDICOID


WHERE 
		C.CONVENIOID NOT IN ( SELECT MCP2.CONVENIOID FROM MEDCONVENIOSNAOATENDIDOS MCP2 WITH(NOLOCK) WHERE MCP2.MEDICOID = M.MEDICOID) AND
		C.SUSPENSO = 'F' AND
		P.SUSPENSO = 'F' 
		--AND C.CONVENIOCOD LIKE '00%'
		AND EXISTS (SELECT MEDICOID FROM HORARIOS WHERE HORARIOS.MEDREAID=M.MEDICOID AND HORARIOS.DATA>=GETDATE() GROUP BY HORARIOS.MEDREAID)
		--AND M.MEDICOID = 2757
		--AND C.CONVENIOCOD ='00608'
GO

