USE [BKP_MEDICAL]
GO

/****** Object:  View [dbo].[TT_ACTIVITIES]    Script Date: 11/05/2022 08:20:53 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO






/*
SELECT * FROM TIPOTEXTOINFO
SELECT * FROM PROCTEXTOINFO IDINFO WHERE PROCID=404
SELECT * FROM TEXTOSINFORMATIVOS INFO WHERE DESCRICAO ='RM ABDOME SUPERIO C/S CONTRAST'
SELECT * FROM TIPOTEXTOINFO TIPOT


	*/


ALTER VIEW [dbo].[TT_ACTIVITIES] AS
SELECT 
	ISNULL(CAST(P.PROCID AS varchar(50)), ' 0') + '_' + CAST(P.MNEMONICO AS varchar) AS ACTIVITY_LID,
	LEFT(CAST(P.DESCRICAO AS varchar(50)),50) AS ACTIVITY_NAME,
	S.DESCRICAO AS ACTIVITY_GROUP_NAME,
	S.SETORID AS ACTIVITY_GROUP_LID,
	CAST(P.TEMPOEXECUCAO AS int) AS ACTIVITY_DURATION,
	'' AS ACTIVITY_PRICE,
	'' AS ACTIVITY_NOTICE,
	 INFO.TEXTO AS ACTIVITY_PREPARATION,
	 CASE 
		WHEN TIPOT.INTERNET = 'T' THEN 1
		ELSE 0 END AS WEB_ENABLED

FROM 
	PROCEDIMENTOS P
INNER JOIN SETORES S ON
S.SETORID= P.SETORID
INNER JOIN PROCTEXTOINFO IDINFO ON IDINFO.PROCID = P.PROCID 
INNER JOIN TEXTOSINFORMATIVOS INFO ON INFO.TEXTOINFOID = IDINFO.TEXTOINFOID
INNER JOIN TIPOTEXTOINFO TIPOT ON TIPOT.TIPOTEXTOID = INFO.TIPOTEXTOID AND TIPOT.INTERNET='T'
WHERE 
	P.INATIVO = 'F'

	AND EXISTS  (SELECT * FROM LIVROSPROCEDIMENTOS WHERE LIVROSPROCEDIMENTOS.PROCID=P.PROCID)
 
--WHERE P.MNEMONICO='RMABDOME'





GO

