USE [BKP_MEDICAL]
GO

/****** Object:  View [dbo].[TT_ACTIVITIES_AVAILABILITIES]    Script Date: 11/05/2022 08:21:06 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO




ALTER VIEW [dbo].[TT_ACTIVITIES_AVAILABILITIES] AS

SELECT  

CAST(LP.PROCID AS VARCHAR) + '_' + CAST(PX.MNEMONICO AS VARCHAR) AS ACTIVITY_LID,
CAST(CAST(H.DATA AS INT) AS VARCHAR) + '_' + CAST(CAST(H.LIVROID AS varchar) + '_' + CAST(CAST(H.HORA AS INT) AS VARCHAR) + '_' + ' ' + '_' + CAST(LIV.UNIDADEID AS VARCHAR) AS varchar) AS  AVAILABILITY_LID
/*
,
LIV.LIVROID,
LP.PROCID
,
PX.DESCRICAO,
LIM.QTDLIMITE,
(SELECT COUNT(*) FROM TT_RESERVATIONS RE WHERE CONVERT(datetime,RE.APP_DATE,103)=CAST(H.DATA AS date) AND RE.ACTIVITY_LID=PX.PROCID) AS QTD_RESERVAS
*/
FROM HORARIOS H

INNER JOIN LIVROS LIV ON 
H.LIVROID = LIV.LIVROID

INNER JOIN LIVROSPROCEDIMENTOS LP ON
LP.LIVROID=LIV.LIVROID

INNER JOIN PROCEDIMENTOS PX ON
PX.PROCID=LP.PROCID 

LEFT JOIN LIVINTLIMPROC LIM
ON LIM.LIVROID=H.LIVROID AND LIM.PROCID=LP.PROCID AND LIM.DATAINI>=H.DATA AND LIM.DATAFIM<=H.DATA


WHERE 
 PX.INATIVO ='F' AND
 H.STATUS = 'L' AND
(SELECT COUNT(*) 
FROM TT_RESERVATIONS RE 
WHERE CONVERT(datetime,RE.APP_DATE,103)=CAST(H.DATA AS date) 
AND RE.ACTIVITY_LID=PX.PROCID
AND PARSENAME(replace(RE.RESOURCE_LID, 'E','.'), 1)=H.LIVROID)<
CASE WHEN LIM.QTDLIMITE>0 THEN LIM.QTDLIMITE ELSE 1000000 END
/*
AND H.LIVROID=20
AND LP.PROCID='839'
AND H.DATA='2021-12-08 00:00:00.000'
*/









GO

