USE [BKP_MEDICAL]
GO

/****** Object:  View [dbo].[TT_INSURANCES_RESOURCES_OLD]    Script Date: 19/04/2022 09:51:33 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO






ALTER VIEW [dbo].[TT_INSURANCES_RESOURCES_OLD] AS

/*
SELECT * FROM LIVROS
SELECT * FROM CONVENIOS
SELECT * FROM CONVENIOSPLANOS WHERE CONVENIOID ='1'
SELECT * FROM MEDICOSCONVPLANOS
SELECT * FROM VW_AGENDA
SELECT * FROM LIVROSCONVENIOS
SELECT * FROM EQUIPAMENTOS
SELECT * FROM UNIDADES

*/



SELECT DISTINCT
CONVERT(VARCHAR(50), C.CONVENIOID) + '_' + CONVERT(VARCHAR(50),C.CONVENIOCOD) + '_' + CONVERT(VARCHAR(50),P.PLANOID) AS INSURANCE_LID,
ISNULL(CAST(MCP.MEDICOID AS varchar), '') + '_' + ISNULL(CAST(LC.LIVROID  AS VARCHAR), '') AS RESOURCE_LID
FROM CONVENIOS C
LEFT JOIN CONVENIOSPLANOS P ON
P.CONVENIOID = C.CONVENIOID
LEFT JOIN MEDICOSCONVPLANOS MCP ON 
MCP.CONVENIOID = P.CONVENIOID
LEFT JOIN LIVROSCONVENIOS LC ON 
LC.CONVENIOID = C.CONVENIOID

WHERE C.SUSPENSO = 'F' AND
P.SUSPENSO = 'F' AND
C.CONVENIOCOD LIKE '00%' 
--AND C.CONVENIOID ='1'





GO


