USE [smart_homolog]
GO

/****** Object:  View [dbo].[TT_AVAILABILITIES]    Script Date: 11/05/2022 15:00:54 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER VIEW [dbo].[TT_AVAILABILITIES] AS
SELECT 
CAST(GH.HOR_MED AS VARCHAR)+'_'+CAST(GH.HOR_CTF AS VARCHAR)+'_'+CAST(GH.HOR_LOC AS VARCHAR)+'_'+CAST(CAST(GH.DATA AS INT) AS VARCHAR) +'_' +GH.HORARIO_INICIO AS  AVAILABILITY_LID
,GH.HOR_DIA AS R_WORKING_DAY
,GH.HORARIO_INICIO AS R_START_TIME
,GH.HORARIO_TERMINO AS R_END_TIME
,CONVERT(VARCHAR,GH.DATA,103 ) AS R_START_DAY
,CONVERT(VARCHAR,GH.DATA,103 ) AS R_END_DAY
,GH.HOR_MED AS RESOURCE_LID
,GH.ID_UNIDADE AS LOCATION_LID

from EX_GRADE_HORARIA GH
WHERE GH.SITUACAO='DISPONIVEL'
GO

