USE [smart_homolog]
GO

/****** Object:  View [dbo].[TT_LOCATIONS]    Script Date: 11/05/2022 15:01:43 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER VIEW [dbo].[TT_LOCATIONS]
 AS
 SELECT 
 STR_COD AS LOCATION_LID, 
 STR_NOME AS LOCATION_NAME , 
 '' AS LOCATION_NOTICE, 
 ISNULL(rtrim(EMP_END),'') + ISNULL(COALESCE(', Nº '+ EMP.emp_end_num, NULL),'') + ISNULL(COALESCE(' - ' + EMP.emp_comp, NULL),'') AS LOCATION_ADDRESS, 
 ISNULL(emp_cep,'') as LOCATION_ZIP_CODE, 
 ISNULL(CDE_NOME,'') AS LOCATION_CITY, 
 ISNULL(EMP.EMP_UFE_SIGLA,'') AS LOCATION_PROVINCE, 
 '' AS LOCATION_REGION, 
 ISNULL(PAI_NOME,'BRASIL') AS LOCATION_COUNTRY, 
 1 AS WEB_ENABLED
 FROM GCC 
 INNER JOIN STR ON 
 GCC_STR_COD = STR_COD 
 INNER JOIN EMP ON 
 STR_EMP_COD = EMP_COD 
 LEFT OUTER JOIN CDE ON 
 EMP_CDE_COD = CDE_COD 
 LEFT OUTER JOIN PAI ON
 CDE_PAI_SIGLA = PAI_SIGLA
GO

