USE [smart_homolog]
GO

/****** Object:  View [dbo].[TT_RESOURCES]    Script Date: 11/05/2022 15:02:15 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



ALTER VIEW [dbo].[TT_RESOURCES]
AS
SELECT DISTINCT 
PSV_COD AS RESOURCE_LID, 
DBO.F_PRIMEIRONOME(RTRIM(LTRIM(PSV_NOME))) AS RESOURCE_FIRST_NAME, 
DBO.F_SOBRENOME(RTRIM(LTRIM(PSV_NOME))) AS RESOURCE_SECOND_NAME, 
PSV_CELULAR AS RESOURCE_MOBILE_PHONE, 
PSV_EMAIL AS RESOURCE_EMAIL,
'' AS RESOURCE_ID_NUMBER, 
HOR.HOR_STR_COD AS LOCATION_LID, 
1 AS WEB_ENABLED, 
'' AS AVAILABILITIES_STEP
FROM PSV 
INNER JOIN HOR ON 
HOR_MED = PSV_COD
WHERE PSV_TIPO IN ('M')
AND PSV_COD <>0
GO

