USE [smart_homolog]
GO

/****** Object:  View [dbo].[TT_RESERVATIONS]    Script Date: 11/05/2022 15:01:59 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER VIEW [dbo].[TT_RESERVATIONS] AS
SELECT 
AGM_ID AS APP_LID,
'' AS APP_TIME,
SUBSTRING(CAST(CONVERT(date,AGM_HINI,127) AS VARCHAR),1,10) AS APP_DATE,
SUBSTRING(CAST(CONVERT(time,AGM_HINI,114) AS VARCHAR),1,5) AS APP_START_TIME,
SUBSTRING(CAST(CONVERT(time,AGM_HFIM,114) AS VARCHAR),1,5) AS APP_END_TIME,
'' APP_PRICE,
0 APP_SHOW,
SUBSTRING(CAST(CONVERT(date,AGM_DTMRC,127) AS VARCHAR),1,10) AS APP_CREATED,
SUBSTRING(CAST(CONVERT(date,AGM_DTMRC,127) AS VARCHAR),1,10) AS APP_MODIFIED,
case when PAC.PAC_REG = 0 then '' else CAST(PAC.PAC_REG AS VARCHAR) end USER_LID,
'' AS USER_TIME,
PAC.PAC_NOME AS USER_FIRST_NAME,
'' AS USER_SECOND_NAME,
'' AS USER_THIRD_NAME,
'' AS USER_ID_NUMBER,
PAC.PAC_FONE AS USER_LANDLINE_PHONE,
NULL AS USER_WORK_FONE,
PAC.PAC_EMAIL AS USER_EMAIL,
'' AS USER_DATE_OF_BIRTH,
'' AS USER_PLACE_OF_BIRTH,
PAC.PAC_SEXO AS USER_GENDER,
PAC.PAC_CEP AS USER_ZIP_CODE,
PAC.PAC_END AS USER_STREET,
PAC.PAC_END_NUM AS USER_STREET_NUMBER,
PAC.PAC_CID AS USER_CITY,
'' AS USER_PROVINCE,
PAC.PAC_UF AS USER_REGION,
'BRASIL' AS USER_COUNTRY,
PAC.PAC_CELULAR AS USER_MOBILE_PHONE,
'' AS USER_LANGUAGE,
'' AS USER_PRIVACY,
'' AS USER_PRIVACY_PROMOTIONS,
'' AS COMMUNICATION_PREFERENCES,
AGM.AGM_MED AS RESOURCE_LID,
AGM.AGM_ADP_COD AS ACTIVITY_LID,
AGM.AGM_CNV_COD AS INSURANCE_LID,
AGM.AGM_LOC AS LOCATION_LID,
CASE 
	WHEN AGM.AGM_STAT = 'A' THEN 'APROVED' 
	WHEN AGM.AGM_STAT = 'C' THEN 'CANCELED' 
	WHEN AGM.AGM_STAT = 'E' THEN 'APROVED' 
	ELSE 'NO-SHOW' 
END STATUS,
'' NOTES,
NULL AS APP_OWNER_LID,
'' AS APP_OWNER_TID,
'' AS APP_OWNER_NAME,
0 AS APP_CUSTOM_0,
0 AS APP_CUSTOM_1,
'' AS APP_CUSTOM_2,
'' AS APP_CUSTOM_3,
'' AS APP_CUSTOM_4

FROM AGM WITH(NOLOCK)

LEFT JOIN PAC WITH(NOLOCK) ON
PAC.PAC_REG=AGM.AGM_PAC

WHERE 1=1
AND AGM.AGM_HINI>='2022-01-01'
--AND AGM_PAC=0
--AGM.AGM_HINI >getdate()


GO

