USE [BKP_MEDICAL]
GO

/****** Object:  View [dbo].[TT_ACTIVITIES_AVAILABILITIES_OLD]    Script Date: 19/04/2022 09:33:18 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



ALTER VIEW [dbo].[TT_ACTIVITIES_AVAILABILITIES_OLD] AS

SELECT  

L.PROCID AS ACTIVITY_LID,
CAST(CAST(H.DATA AS INT) AS VARCHAR) + '_' + CAST(CAST(H.LIVROID AS varchar) + '_' + CAST(CAST(H.HORA AS INT) AS VARCHAR) + '_' + ' ' + '_' + CAST(LIV.UNIDADEID AS VARCHAR) AS varchar) AS  AVAILABILITY_LID

FROM HORARIOS H
INNER JOIN LIVROSPROCEDIMENTOS L ON L.LIVROID = H.LIVROID
INNER JOIN PROCEDIMENTOS P ON P.PROCID = L.LIVROID
INNER JOIN LIVROS LIV ON LIV.LIVROID = L.LIVROID
WHERE 
 P.INATIVO ='F' AND
 --H.DATA  = '2022-01-03 00:00:00.000'  AND 
 H.STATUS = 'L' 
 --AND LIV.LIVROID= 13
  


GO

