USE [BKP_MEDICAL]
GO

/****** Object:  View [dbo].[TT_INSURANCES_ACTIVITIES_1104]    Script Date: 19/04/2022 09:50:55 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO













/*
select * from LIVROSPROCEDIMENTOS where PROCID= 337
select * from PROCTABELASITENS where PROCID = 337 and PROCTABID = 607
select * from PROCEDIMENTOS where PROCID =337
select * from LIVROSCONVENIOS 
SELECT * FROM LIVROS



SELECT * FROM PROCEDIMENTOS P
INNER JOIN LIVROSPROCEDIMENTOS LP ON LP.PROCID = P.PROCID
WHERE LP.PROCID = 337


*/
ALTER VIEW  [dbo].[TT_INSURANCES_ACTIVITIES_1104] AS 
SELECT DISTINCT

	CONVERT(VARCHAR(50), C.CONVENIOID) + '_' + CONVERT(VARCHAR(50),C.CONVENIOCOD) + + '_' + CONVERT(VARCHAR(50),ISNULL(CP.PLANOID,C.CONVENIOID)) AS INSURANCE_LID,
	CAST(LP.PROCID AS VARCHAR) AS ACTIVITY_LID
	,STR(CAST(ISNULL(VLR.QUANTCH, 0)AS int) + CAST(ISNULL(VLR.QUANTCO, 0)AS int) + CAST(ISNULL(VLR.QUANTFILME, 0)AS int), 12,2) AS ACTIVITY_PRICE -- inserir preço da tabela particular <> 22 = 0

	
FROM

	CONVENIOS C
	INNER JOIN CONVENIOSPLANOS CP ON CP.CONVENIOID = C.CONVENIOID
	AND CP.PLANOID=C.PLANOID
	INNER JOIN LIVROSCONVENIOS LC ON LC.CONVENIOID = C.CONVENIOID
	INNER JOIN LIVROS L ON L.LIVROID = LC.LIVROID 
	INNER JOIN LIVROSPROCEDIMENTOS LP ON LP.LIVROID = L.LIVROID
	INNER JOIN PROCEDIMENTOS P ON P.PROCID = LP.PROCID
	LEFT JOIN PROCTABELASITENS VLR ON 	VLR.PROCID = P.PROCID
	AND VLR.PROCTABID = CP.PROCTABID
	
WHERE 

		LP.LIVROID = L.LIVROID AND
		--P.PROCID = 319 AND
		C.SUSPENSO = 'F' AND
		CP.SUSPENSO = 'F' 
		--AND
		--C.CONVENIOCOD LIKE '00%' 
		 --order by INSURANCE_LID

--SELECT * FROM PROCTABELASITENS WHERE PROCID = 319 AND PROCTABID = 607
	









GO


