USE [BKP_MEDICAL]
GO

/****** Object:  View [dbo].[TT_INSURANCES_ACTIVITIES]    Script Date: 11/05/2022 08:22:18 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


ALTER VIEW  [dbo].[TT_INSURANCES_ACTIVITIES] AS 
SELECT DISTINCT
CONVERT(VARCHAR(50), CONV.CONVENIOID) + '_' + CONVERT(VARCHAR(50),CONV.CONVENIOCOD) + + '_' + CONVERT(VARCHAR(50),ISNULL(PLA.PLANOID,CONV.CONVENIOID)) AS INSURANCE_LID
,CAST(PRO.PROCID AS VARCHAR) + '_' + CAST(PRO.MNEMONICO AS VARCHAR) AS ACTIVITY_LID
,STR(CAST(ISNULL(VLR.QUANTCH, 0)AS int) + CAST(ISNULL(VLR.QUANTCO, 0)AS int) + CAST(ISNULL(VLR.QUANTFILME, 0)AS int), 12,2) AS ACTIVITY_PRICE -- inserir preço da tabela particular <> 22 = 0

FROM PROCEDIMENTOS PRO with(nolock)
INNER JOIN PROCTABELASITENS VLR with(nolock) ON
VLR.PROCID=PRO.PROCID
INNER JOIN PROCTABELAS TAB with(nolock) ON
TAB.PROCTABID=VLR.PROCTABID
INNER JOIN CONVENIOSPLANOS PLA with(nolock) ON
PLA.PROCTABID=TAB.PROCTABID 
INNER JOIN CONVENIOS CONV with(nolock) ON
CONV.CONVENIOID=PLA.CONVENIOID

WHERE
CONV.PLANOID=PLA.PLANOID
AND PRO.INATIVO='F'
and PLA.SUSPENSO='F'
AND CONV.SUSPENSO='F'
AND PRO.PROCID NOT IN (SELECT CPP.PROCID FROM CONVENIOSPLANOSPROC CPP  with(nolock) WHERE CPP.CONVENIOID=CONV.CONVENIOID AND CPP.PLANOID=PLA.PLANOID AND CPP.FORMAVALOR='4')



GO

