USE [BKP_MEDICAL]
GO

/****** Object:  Trigger [dbo].[TT_PAYMENTS_TMP_INSERT]    Script Date: 19/04/2022 10:25:58 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


 /*
 
 SELECT * FROM TT_PAYMENTS_TMP
 SELECT * FROM HORARIOS WHERE DATA = '2021-07-08' AND LIVROID = 8
select * from HORARIOSDADOS where DATA = '2021-07-08' and LIVROID = 8


 */

 
ALTER TRIGGER [dbo].[TT_PAYMENTS_TMP_INSERT]
ON [dbo].[TT_PAYMENTS_TMP]
FOR INSERT
AS
BEGIN

DECLARE
	 @APP_LID VARCHAR(50), -- MESMO APP_LID DA TT_RESERVATION? 
	 @PAYMENT_ACTION VARCHAR(10),
	 @APP_AMOUNT VARCHAR(10),
	 @APP_AMOUNT_FULLPRICE VARCHAR(10),
	 @EXT_ID VARCHAR(50),
	 @APP_PRICE VARCHAR(20),
	 @PAYED VARCHAR(20),
	 @STATUS_TRIGGER VARCHAR(200),
	 @DOCUMENT_LID VARCHAR(1),

	 @MENSAGEM_OLD VARCHAR(400)

SELECT
	 @APP_LID = APP_LID,
	 @PAYMENT_ACTION = PAYMENT_ACTION,
	 @APP_AMOUNT = APP_AMOUNT,
	 @APP_AMOUNT_FULLPRICE = APP_AMOUNT_FULLPRICE,
	 @EXT_ID = EXT_ID,
	 @APP_PRICE = APP_PRICE,
	 @PAYED = PAYED,
	 @STATUS_TRIGGER = STATUS_TRIGGER,
	 @DOCUMENT_LID = DOCUMENT_LID

	 FROM INSERTED 

	 


END



GO


