USE [Xclinic_HML]
GO

/****** Object:  View [dbo].[EXVW_LIVROSCONVENIOS]    Script Date: 11/05/2022 15:16:07 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO





ALTER VIEW [dbo].[EXVW_LIVROSCONVENIOS]
AS
SELECT DISTINCT
CONVERT(VARCHAR(50), C.CONVENIOID) + '_' + CONVERT(VARCHAR(50),C.CONVENIOCOD) + '_' + CONVERT(VARCHAR(50),ISNULL(P.PLANOID,C.CONVENIOID)) AS INSURANCE_LID,
cast(LC.LIVROID as varchar)  AS RESOURCE_LID
FROM CONVENIOS C WITH(NOLOCK)
LEFT JOIN CONVENIOSPLANOS P  WITH(NOLOCK) ON P.CONVENIOID = C.CONVENIOID
--AND P.PLANOID=C.PLANOID
--LEFT JOIN MEDICOSCONVPLANOS MCP ON MCP.CONVENIOID = P.CONVENIOID 
LEFT JOIN LIVROSCONVENIOS LC  WITH(NOLOCK) ON LC.CONVENIOID = C.CONVENIOID

WHERE C.SUSPENSO = 'F' AND
P.SUSPENSO = 'F' 
--AND C.CONVENIOCOD LIKE '00%' 



GO

