USE [Xclinic_HML]
GO

/****** Object:  View [dbo].[TT_ACTIVITIES]    Script Date: 11/05/2022 15:16:35 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


/*
SELECT * FROM TIPOTEXTOINFO
SELECT * FROM PROCTEXTOINFO IDINFO WHERE PROCID=404
SELECT * FROM TEXTOSINFORMATIVOS INFO WHERE DESCRICAO ='RM ABDOME SUPERIO C/S CONTRAST'
SELECT * FROM TIPOTEXTOINFO TIPOT
*/

ALTER VIEW [dbo].[TT_ACTIVITIES] AS
SELECT 
	ISNULL(CAST(P.PROCID AS varchar(50)) + '_' + CAST(P.MNEMONICO AS VARCHAR(50)), ' 0') AS ACTIVITY_LID,
	LEFT(CAST(P.DESCRICAO AS varchar(50)),50) AS ACTIVITY_NAME,
	S.DESCRICAO AS ACTIVITY_GROUP_NAME,
	S.SETORID AS ACTIVITY_GROUP_LID,
	CAST(P.TEMPOEXECUCAO AS int) AS ACTIVITY_DURATION,
	'' AS ACTIVITY_PRICE,
	'' AS ACTIVITY_NOTICE,
	 '' AS ACTIVITY_PREPARATION,
	 CASE 
		WHEN TIPOT.INTERNET = 'T' THEN 1
		ELSE 0 END AS WEB_ENABLED

FROM PROCEDIMENTOS P
left JOIN SETORES S ON
S.SETORID= P.SETORID
LEFT JOIN PROCTEXTOINFO IDINFO ON IDINFO.PROCID = P.PROCID 
LEFT JOIN TEXTOSINFORMATIVOS INFO ON INFO.TEXTOINFOID = IDINFO.TEXTOINFOID
LEFT JOIN TIPOTEXTOINFO TIPOT ON TIPOT.TIPOTEXTOID = INFO.TIPOTEXTOID AND TIPOT.INTERNET='T'
WHERE 
	P.INATIVO = 'F'
 
--WHERE P.MNEMONICO='RMABDOME'

GO

