USE [Xclinic_HML]
GO

/****** Object:  View [dbo].[TT_EPISODES]    Script Date: 11/05/2022 15:17:34 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO




/*

SELECT CONVERT(VARCHAR(MAX ), CONVERT (VARBINARY(MAX),LAUDO ))
FROM FATURALAUDO WHERE PACIENTEID = 115532


SELECT CONVERT(VARCHAR(MAX ), CONVERT (VARBINARY(MAX),LAUDO ))
FROM LAUDOS_VERSOES WHERE PACIENTEID = 124777

SELECT * FROM LAUDOS_VERSOES WHERE PACIENTEID = 124777 -- VARIOS LAUDOS
SELECT * FROM FATURA WHERE FATURAID= 124777
SELECT * FROM FATURALAUDO WHERE PACIENTEID = 124777
SELECT * FROM LAUDOCONCLUSAO WHERE PACIENTEID = 124777
SELECT * FROM PROCEDIMENTOS WHERE DESCRICAO LIKE '%LOMBO-SACRA%'
SELECT * FROM PROCEDIMENTOS 

EXEC sp_help FATURALAUDO

*/

ALTER VIEW [dbo].[TT_EPISODES] AS 

--SELECT * FROM FATURA WHERE PACIENTEID= 124777

SELECT
	F.FATURAID AS EPISODE_LID,
	'CATEGORY' AS CATEGORY,
	LV.STATUS AS SATUS,
	CONVERT(VARCHAR(10),LV.DATAHORA, 103) DOCUMENT_DATE,
	F.LAUDONOMEEXAME AS DOCUMENT_NAME,
	'DESCRIPTION' AS DESCRIPTION,
	F.PACIENTEID  AS USER_LID,
	'USER_TID' AS USER_TID,
	F.PACIENTEID AS USER_ID_NUMBER,
	P.TELEFONE AS USER_MOBILE_PHONE,
	'1' AS USER_PRIVACY,
	'111' AS COMMUNICATION_PREFERENCES,
	'Pt-Br' AS USER_LANGUAGE,
	F.FATURAID AS APP_LID



FROM FATURA F
INNER JOIN FATURALAUDO FL ON
FL.FATURAID = F.FATURAID
INNER JOIN LAUDOS_VERSOES LV ON
LV.FATURAID = F.FATURAID
INNER JOIN PACIENTE P ON
P.PACIENTEID = F.PACIENTEID
INNER JOIN LAUDOCONCLUSAO LC ON
LC.FATURAID = LV.FATURAID

WHERE 
LV.STATUS = 'I' AND
P.PACIENTEID = 124777


GO

