USE [Xclinic_HML]
GO

/****** Object:  View [dbo].[TT_EPISODE_DOCUMENTS]    Script Date: 11/05/2022 15:17:22 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



/*
SELECT * FROM PIXEON_DOCUMENT

SELECT CONVERT(VARCHAR(MAX ), CONVERT (VARBINARY(MAX),LAUDO ))
FROM FATURALAUDO WHERE PACIENTEID = 115532

ACCESIONNUMBER = 1624881

select * from tt_reservations_tmp
SELECT * FROM TT_RESERVATIONS

SELECT CONVERT(VARCHAR(MAX ), CONVERT (VARBINARY(MAX),LAUDO ))
FROM LAUDOS_VERSOES WHERE PACIENTEID = 124777

SELECT * FROM LAUDOS_VERSOES WHERE PACIENTEID = 124777 -- VARIOS LAUDOS
SELECT * FROM FATURA WHERE FATURAID= 1356987
SELECT * FROM FATURALAUDO WHERE PACIENTEID = 124777
SELECT * FROM LAUDOCONCLUSAO WHERE PACIENTEID = 124777
SELECT * FROM PROCEDIMENTOS WHERE DESCRICAO LIKE '%LOMBO-SACRA%'
SELECT * FROM PROCEDIMENTOS 

EXEC sp_help FATURALAUDO

--SELECT * FROM CLICKVITA_EXAMES WHERE PACIENTEID = 124777
SELECT * FROM INTEGRA_PACS where DATA > '2021-05-01'
SELECT * FROM INTEGRA_PACS WHERE ACCESSIONNUMBER='1598958'

LINK: http://177.43.232.82:8008/study/auth/1?a=1624881&t=1665857952&h=c2d2dc78ebd832752459bce4633b509ec6e7b596&r=1


SELECT * FROM PIXEON_PATIENT_HISTORIC
*/

--SELECT HASHBYTES('SHA1', )

--SELECT dbo.UNIX_TIMESTAMP(GETDATE())

ALTER VIEW [dbo].[TT_EPISODE_DOCUMENTS] AS



SELECT 
	F.FATURAID AS DOCUMENT_LID,
	F.FATURAID AS EPISODE_LID, -- VERIICAR SE VAI SER ESSE O ID
	LV.STATUS AS STATUS,
	'DOCUMENT_CATEGORY' AS DOCUMENT_CATEGORY,
	'RTF' AS DOCUMENT_TYPE,
	CONVERT(VARCHAR(10),LV.DATAHORA, 103) DOCUMENT_DATE,
	LEFT(RIGHT(CONVERT(VARCHAR, LV.DATAHORA, 120), 9),6) AS DOCUMENT_TIME,
	F.LAUDONOMEEXAME AS DOCUMENT_NAME,
	--DBO.FNC_GET_URL('/study/auth/1?','http://177.43.232.82:8008','d7cd7fa14746db1e6f2e9ade4e01377eb2dfb229',IP.ACCESSIONNUMBER,'','') AS DOCUMENT_URL,
	DBO.FNC_GET_URL('/study/auth/1?','http://ultrimagemjf.dualsuperdns.com:8008','d7cd7fa14746db1e6f2e9ade4e01377eb2dfb229',IP.ACCESSIONNUMBER,'','') AS DOCUMENT_URL,
	'\\192.168.1.152\tuotempo_laudos$\' + cast(IP.ACCESSIONNUMBER as varchar)+ '.pdf' AS DOCUMENT_CONTENT
	

FROM FATURA F
INNER JOIN FATURALAUDO FL ON
FL.FATURAID = F.FATURAID
INNER JOIN LAUDOS_VERSOES LV ON
LV.FATURAID = F.FATURAID
INNER JOIN PACIENTE P ON
P.PACIENTEID = F.PACIENTEID
INNER JOIN LAUDOCONCLUSAO LC ON
LC.FATURAID = LV.FATURAID
INNER JOIN INTEGRA_PACS IP ON
IP.FATURAID = F.FATURAID

WHERE 
LV.STATUS = 'I' 
--AND P.PACIENTEID = 124777
--AND LV.DATAHORA > '2021-06-10'



GO

