USE [Xclinic_HML]
GO

/****** Object:  View [dbo].[TT_RESOURCES_ACTIVITIES]    Script Date: 11/05/2022 15:19:31 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



ALTER VIEW  [dbo].[TT_RESOURCES_ACTIVITIES]  AS

SELECT DISTINCT 
ACTIVITIES.* FROM (

SELECT DISTINCT 
CAST(LP.LIVROID AS varchar)+'E' AS RESOURCE_LID,
CAST(P.PROCID AS VARCHAR) + '_' + CAST(P.MNEMONICO AS VARCHAR) AS ACTIVITY_LID,
0 AS ACTIVITY_DURATION,
'ACTIVITY_PRICE'  AS ACTIVITY_PRICE
FROM 
LIVROSPROCEDIMENTOS LP
INNER JOIN PROCEDIMENTOS P ON P.PROCID = LP.PROCID
--INNER JOIN HORARIOS H ON H.LIVROID = LP.LIVROID
INNER JOIN LIVROSINTERVALOS LI ON LI.LIVROID = LP.LIVROID
WHERE
--H.STATUS='L'
--AND H.MEDREAID IS NULL
LI.MEDREAID IS NULL

UNION ALL

SELECT DISTINCT 
CAST(LI.MEDREAID AS VARCHAR(100)) AS RESOURCE_LID,
CAST(P.PROCID AS VARCHAR) + '_' + CAST(P.MNEMONICO AS VARCHAR) AS ACTIVITY_LID,
0 AS ACTIVITY_DURATION,
'ACTIVITY_PRICE'  AS ACTIVITY_PRICE
FROM 
LIVROSPROCEDIMENTOS LP
INNER JOIN PROCEDIMENTOS P ON P.PROCID = LP.PROCID
--INNER JOIN HORARIOS H ON H.LIVROID = LP.LIVROID
INNER JOIN LIVROSINTERVALOS LI ON LI.LIVROID = LP.LIVROID
WHERE
--H.STATUS='L'
--AND H.DATA>=GETDATE()
LI.MEDREAID IS NOT NULL AND LI.MEDREAID!=''
AND NOT EXISTS (SELECT * FROM LIVROSINTERVALOSEXAMES LE WHERE LI.CONTADOR=LE.CONTADOR AND LI.LIVROID=LE.LIVROID)
--AND H.MEDREAID='13734'

UNION ALL

SELECT DISTINCT 
CAST(LI.MEDREAID AS VARCHAR(100)) AS RESOURCE_LID,
CAST(P.PROCID AS VARCHAR) + '_' + CAST(P.MNEMONICO AS VARCHAR) AS ACTIVITY_LID,
0 AS ACTIVITY_DURATION,
'ACTIVITY_PRICE'  AS ACTIVITY_PRICE
FROM 
LIVROSPROCEDIMENTOS LP
INNER JOIN PROCEDIMENTOS P ON P.PROCID = LP.PROCID
--INNER JOIN HORARIOS H ON H.LIVROID = LP.LIVROID
INNER JOIN LIVROSINTERVALOS LI ON LI.LIVROID = LP.LIVROID
INNER JOIN LIVROSINTERVALOSEXAMES LE ON 
LI.CONTADOR=LE.CONTADOR AND LI.LIVROID=LE.LIVROID AND LE.PROCID=P.PROCID
WHERE
--H.STATUS='L'
--AND H.DATA>=GETDATE()
LI.MEDREAID IS NOT NULL AND LI.MEDREAID!=''
AND EXISTS (SELECT * FROM LIVROSINTERVALOSEXAMES LE WHERE LI.CONTADOR=LE.CONTADOR AND LI.LIVROID=LE.LIVROID)

) ACTIVITIES




GO

